#create_clock -name in_clk100 -period 10 [get_ports in_clk100]
#set_property PACKAGE_PIN AL15 [get_ports in_clk100]
#set_property IOSTANDARD LVCMOS18 [get_ports in_clk100]
set_property PACKAGE_PIN BJ43 [get_ports sys_clk_p]
set_property PACKAGE_PIN BJ44 [get_ports sys_clk_n]
set_property IOSTANDARD  DIFF_SSTL12 [get_ports sys_clk_p]
set_property IOSTANDARD  DIFF_SSTL12 [get_ports sys_clk_n]
create_clock -name sys_clk -period 10 [get_ports sys_clk_p]
#create_clock -name sys_clk -period 10 [get_ports sys_clk_p]
#set_property LOC [get_package_pins -of_objects [get_bels [get_sites -filter {NAME =~ *COMMON*} -of_objects [get_iobanks -of_objects [get_sites GTYE4_CHANNEL_X1Y7]]]/REFCLK0P]] [get_ports sys_clk_p]
#set_property LOC [get_package_pins -of_objects [get_bels [get_sites -filter {NAME =~ *COMMON*} -of_objects [get_iobanks -of_objects [get_sites GTYE4_CHANNEL_X1Y7]]]/REFCLK0N]] [get_ports sys_clk_n]
set_false_path -from [get_ports cpu_resetn]
set_property PULLUP true [get_ports cpu_resetn]
set_property IOSTANDARD LVCMOS18 [get_ports cpu_resetn]
set_property PACKAGE_PIN BH26 [get_ports cpu_resetn]
set_property CONFIG_VOLTAGE 1.8 [current_design]
set_property PACKAGE_PIN D32 [get_ports bbq_out]
set_property IOSTANDARD  LVCMOS18 [get_ports bbq_out]