set_property SRC_FILE_INFO {cfile:/home/pnic/mkxue/BBQ_BM/BBQ_BM.srcs/constrs_1/new/top_constrs.xdc rfile:../../../BBQ_BM.srcs/constrs_1/new/top_constrs.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BJ43 [get_ports sys_clk_p]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BJ44 [get_ports sys_clk_n]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BH26 [get_ports cpu_resetn]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D32 [get_ports bbq_out]
