# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/gabber/FUDAN/workspace/SBM_0728/BBQ_BM/BBQ_BM.srcs/sources_1/ip/hbm_0/hbm_0.xci
# IP: The module: 'hbm_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gabber/FUDAN/workspace/SBM_0728/BBQ_BM/BBQ_BM.gen/sources_1/ip/hbm_0/hdl/par/hbm_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'hbm_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/gabber/FUDAN/workspace/SBM_0728/BBQ_BM/BBQ_BM.gen/sources_1/ip/hbm_0/hdl/par/hbm_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hbm_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/gabber/FUDAN/workspace/SBM_0728/BBQ_BM/BBQ_BM.srcs/sources_1/ip/hbm_0/hbm_0.xci
# IP: The module: 'hbm_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gabber/FUDAN/workspace/SBM_0728/BBQ_BM/BBQ_BM.gen/sources_1/ip/hbm_0/hdl/par/hbm_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'hbm_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/gabber/FUDAN/workspace/SBM_0728/BBQ_BM/BBQ_BM.gen/sources_1/ip/hbm_0/hdl/par/hbm_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hbm_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
